name: Ui Test
on: pull_request
jobs:
  ui-tests:
    timeout-minutes: 25
    runs-on: ubuntu-latest
    env:
      androidApiVersion: 29
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Fetch Gradle Wrapper Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
      - name: Fetch Gradle Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/Config.kt') }}
      - name: Fetch AVD Cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ runner.os }}-${{ env.androidApiVersion }}
      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.androidApiVersion }}
          arch: x86
          ram-size: 2048M
          force-avd-creation: false
          disable-animations: true
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: echo "Generated AVD snapshot for caching."
      - name: 🤖 Run Ui Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.androidApiVersion }}
          arch: x86_64
          profile: Nexus 4
          ram-size: 3072M
          force-avd-creation: false
          disable-animations: true
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: ./gradlew connectedCheck
      - name: Publish Ui Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Ui Test Results
          comment_title: "Ui Test Results"
          files: '**/androidTest-results/**/*.xml'
